services:
  cassandra-init:
    image: cassandra:latest
    restart: "no"
    entrypoint: >
      cqlsh cassandra -e
      "CREATE KEYSPACE IF NOT EXISTS review_keyspace
       WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};"
    networks:
      - dotohtwolocalinfra

  review-api:
    build:
      context: .
      args:
        CODEARTIFACT_AUTH_TOKEN: ${CODEARTIFACT_AUTH_TOKEN}
    ports:
      - "8081:8081"
    environment:
      - SPRING_CASSANDRA_CONTACT_POINTS=cassandra
      - SPRING_CASSANDRA_LOCAL_DATACENTER=datacenter1
      - SPRING_CASSANDRA_KEYSPACE_NAME=review_keyspace
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_DATA_REDIS_HOST=redis
    depends_on:
      cassandra-init:
        condition: service_completed_successfully
    networks:
      - default
      - dotohtwolocalinfra

networks:
  dotohtwolocalinfra:
    external: true
